import cgiServer

xiangqingDic = {
    "head":{"auth":None,"errcode":0},
	"id":6565454,
	"name":"黔阳，芙蓉楼",
	"addr":"黔阳，芙蓉楼，王昌龄",
	"cmtscore":2.1,
	"cmtusertotal":50,
	"OpenTimeDesc":"8:00-18:00",
	"star":2,
	"lon":102.232512,
	"lat":122.254563,
	"imgurls":["127.0.0.1:8086/img/wow.jpg"],
	"prds":[
		{
			"pid":565656,
			"pname":"黔阳，芙蓉楼，周边不一样的民族风雨楼，吊脚楼",
			"ismaster":True,
			"painfos":{
				"atname":"附加信息标题",
				"astname":"附加信息子标签",
				"painfods":{
					"ddetail":"古龙标芙蓉楼，座落在沅、舞水汇流之处的黔城镇，为古典园林建筑，占地4250平方米，北廓临江，依林踞阜。筑叠巧思、错落有致，被誉为楚南上游第一胜迹，是历代文人墨客吟诗作画之处，也是唐代著名诗人王昌龄宴宾送客之地。",
					"ishl":True
				}
			},
			"ress":[
				{
					"id":895654,
					"name":"芙蓉楼，历史文化源流久远",
					"mprice":70,
					"price":50,
					"isretcash":True,
					"retc":10,
					"minqt":5,
					"maxqt":1,
					"ismpref":True,
					"isnowuse":True,
					"abdays":1,
					"abtime":"2天",
					"rainfos":[
						{
							"title":"湖南怀化的历史文化，芙蓉楼",
							"subtitle":"黔城",
							"desc":"古龙标芙蓉楼，座落在沅、舞水汇流之处的黔城镇，为古典园林建筑，占地4250平方米，北廓临江，依林踞阜。筑叠巧思、错落有致，被誉为楚南上游第一胜迹，是历代文人墨客吟诗作画之处，也是唐代著名诗人王昌龄宴宾送客之地。"
						}
					],
					"paymode":"O",
					"isinchina":True
				}
			]
		}
	]
}
HttpCGI = cgiServer.HttpServerCGI()
HttpCGI.exportHeadType('json')
HttpCGI.handlerForm(xiangqingDic)